/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as LensRouteRouteImport } from './routes/_lens/route'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as LensHomeRouteImport } from './routes/_lens/home'
import { Route as LensAkademikAdminHomeRouteImport } from './routes/_lens/akademik-admin/home'
import { Route as LensExampleHomeRouteImport } from './routes/_lens/example/home'
import { Route as LensExampleMockRouteImport } from './routes/_lens/example/mock'
import { Route as LensExampleMockServerRouteImport } from './routes/_lens/example/mock-server'
import { Route as LensKurikulumHomeRouteImport } from './routes/_lens/kurikulum/home'
import { Route as LensPenilaianHomeRouteImport } from './routes/_lens/penilaian/home'
import { Route as LensPerkuliahanHomeRouteImport } from './routes/_lens/perkuliahan/home'
import { Route as LensPortofolioHomeRouteImport } from './routes/_lens/portofolio/home'
import { Route as LensSilabusHomeRouteImport } from './routes/_lens/silabus/home'
import { Route as LensSuperAdminHomeRouteImport } from './routes/_lens/super-admin/home'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const LensRouteRoute = LensRouteRouteImport.update({
  id: '/_lens',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const LensHomeRoute = LensHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => LensRouteRoute,
} as any)
const LensAkademikAdminHomeRoute = LensAkademikAdminHomeRouteImport.update({
  id: '/akademik-admin/home',
  path: '/akademik-admin/home',
  getParentRoute: () => LensRouteRoute,
} as any)
const LensExampleHomeRoute = LensExampleHomeRouteImport.update({
  id: '/example/home',
  path: '/example/home',
  getParentRoute: () => LensRouteRoute,
} as any)
const LensExampleMockRoute = LensExampleMockRouteImport.update({
  id: '/example/mock',
  path: '/example/mock',
  getParentRoute: () => LensRouteRoute,
} as any)
const LensExampleMockServerRoute = LensExampleMockServerRouteImport.update({
  id: '/example/mock-server',
  path: '/example/mock-server',
  getParentRoute: () => LensRouteRoute,
} as any)
const LensKurikulumHomeRoute = LensKurikulumHomeRouteImport.update({
  id: '/kurikulum/home',
  path: '/kurikulum/home',
  getParentRoute: () => LensRouteRoute,
} as any)
const LensPenilaianHomeRoute = LensPenilaianHomeRouteImport.update({
  id: '/penilaian/home',
  path: '/penilaian/home',
  getParentRoute: () => LensRouteRoute,
} as any)
const LensPerkuliahanHomeRoute = LensPerkuliahanHomeRouteImport.update({
  id: '/perkuliahan/home',
  path: '/perkuliahan/home',
  getParentRoute: () => LensRouteRoute,
} as any)
const LensPortofolioHomeRoute = LensPortofolioHomeRouteImport.update({
  id: '/portofolio/home',
  path: '/portofolio/home',
  getParentRoute: () => LensRouteRoute,
} as any)
const LensSilabusHomeRoute = LensSilabusHomeRouteImport.update({
  id: '/silabus/home',
  path: '/silabus/home',
  getParentRoute: () => LensRouteRoute,
} as any)
const LensSuperAdminHomeRoute = LensSuperAdminHomeRouteImport.update({
  id: '/super-admin/home',
  path: '/super-admin/home',
  getParentRoute: () => LensRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/login': typeof AuthLoginRoute
  '/home': typeof LensHomeRoute
  '/akademik-admin/home': typeof LensAkademikAdminHomeRoute
  '/example/home': typeof LensExampleHomeRoute
  '/example/mock': typeof LensExampleMockRoute
  '/example/mock-server': typeof LensExampleMockServerRoute
  '/kurikulum/home': typeof LensKurikulumHomeRoute
  '/penilaian/home': typeof LensPenilaianHomeRoute
  '/perkuliahan/home': typeof LensPerkuliahanHomeRoute
  '/portofolio/home': typeof LensPortofolioHomeRoute
  '/silabus/home': typeof LensSilabusHomeRoute
  '/super-admin/home': typeof LensSuperAdminHomeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/login': typeof AuthLoginRoute
  '/home': typeof LensHomeRoute
  '/akademik-admin/home': typeof LensAkademikAdminHomeRoute
  '/example/home': typeof LensExampleHomeRoute
  '/example/mock': typeof LensExampleMockRoute
  '/example/mock-server': typeof LensExampleMockServerRoute
  '/kurikulum/home': typeof LensKurikulumHomeRoute
  '/penilaian/home': typeof LensPenilaianHomeRoute
  '/perkuliahan/home': typeof LensPerkuliahanHomeRoute
  '/portofolio/home': typeof LensPortofolioHomeRoute
  '/silabus/home': typeof LensSilabusHomeRoute
  '/super-admin/home': typeof LensSuperAdminHomeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_lens': typeof LensRouteRouteWithChildren
  '/$': typeof SplatRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_lens/home': typeof LensHomeRoute
  '/_lens/akademik-admin/home': typeof LensAkademikAdminHomeRoute
  '/_lens/example/home': typeof LensExampleHomeRoute
  '/_lens/example/mock': typeof LensExampleMockRoute
  '/_lens/example/mock-server': typeof LensExampleMockServerRoute
  '/_lens/kurikulum/home': typeof LensKurikulumHomeRoute
  '/_lens/penilaian/home': typeof LensPenilaianHomeRoute
  '/_lens/perkuliahan/home': typeof LensPerkuliahanHomeRoute
  '/_lens/portofolio/home': typeof LensPortofolioHomeRoute
  '/_lens/silabus/home': typeof LensSilabusHomeRoute
  '/_lens/super-admin/home': typeof LensSuperAdminHomeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/login'
    | '/home'
    | '/akademik-admin/home'
    | '/example/home'
    | '/example/mock'
    | '/example/mock-server'
    | '/kurikulum/home'
    | '/penilaian/home'
    | '/perkuliahan/home'
    | '/portofolio/home'
    | '/silabus/home'
    | '/super-admin/home'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/login'
    | '/home'
    | '/akademik-admin/home'
    | '/example/home'
    | '/example/mock'
    | '/example/mock-server'
    | '/kurikulum/home'
    | '/penilaian/home'
    | '/perkuliahan/home'
    | '/portofolio/home'
    | '/silabus/home'
    | '/super-admin/home'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_lens'
    | '/$'
    | '/_auth/login'
    | '/_lens/home'
    | '/_lens/akademik-admin/home'
    | '/_lens/example/home'
    | '/_lens/example/mock'
    | '/_lens/example/mock-server'
    | '/_lens/kurikulum/home'
    | '/_lens/penilaian/home'
    | '/_lens/perkuliahan/home'
    | '/_lens/portofolio/home'
    | '/_lens/silabus/home'
    | '/_lens/super-admin/home'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  LensRouteRoute: typeof LensRouteRouteWithChildren
  SplatRoute: typeof SplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_lens': {
      id: '/_lens'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LensRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_lens/home': {
      id: '/_lens/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof LensHomeRouteImport
      parentRoute: typeof LensRouteRoute
    }
    '/_lens/akademik-admin/home': {
      id: '/_lens/akademik-admin/home'
      path: '/akademik-admin/home'
      fullPath: '/akademik-admin/home'
      preLoaderRoute: typeof LensAkademikAdminHomeRouteImport
      parentRoute: typeof LensRouteRoute
    }
    '/_lens/example/home': {
      id: '/_lens/example/home'
      path: '/example/home'
      fullPath: '/example/home'
      preLoaderRoute: typeof LensExampleHomeRouteImport
      parentRoute: typeof LensRouteRoute
    }
    '/_lens/example/mock': {
      id: '/_lens/example/mock'
      path: '/example/mock'
      fullPath: '/example/mock'
      preLoaderRoute: typeof LensExampleMockRouteImport
      parentRoute: typeof LensRouteRoute
    }
    '/_lens/example/mock-server': {
      id: '/_lens/example/mock-server'
      path: '/example/mock-server'
      fullPath: '/example/mock-server'
      preLoaderRoute: typeof LensExampleMockServerRouteImport
      parentRoute: typeof LensRouteRoute
    }
    '/_lens/kurikulum/home': {
      id: '/_lens/kurikulum/home'
      path: '/kurikulum/home'
      fullPath: '/kurikulum/home'
      preLoaderRoute: typeof LensKurikulumHomeRouteImport
      parentRoute: typeof LensRouteRoute
    }
    '/_lens/penilaian/home': {
      id: '/_lens/penilaian/home'
      path: '/penilaian/home'
      fullPath: '/penilaian/home'
      preLoaderRoute: typeof LensPenilaianHomeRouteImport
      parentRoute: typeof LensRouteRoute
    }
    '/_lens/perkuliahan/home': {
      id: '/_lens/perkuliahan/home'
      path: '/perkuliahan/home'
      fullPath: '/perkuliahan/home'
      preLoaderRoute: typeof LensPerkuliahanHomeRouteImport
      parentRoute: typeof LensRouteRoute
    }
    '/_lens/portofolio/home': {
      id: '/_lens/portofolio/home'
      path: '/portofolio/home'
      fullPath: '/portofolio/home'
      preLoaderRoute: typeof LensPortofolioHomeRouteImport
      parentRoute: typeof LensRouteRoute
    }
    '/_lens/silabus/home': {
      id: '/_lens/silabus/home'
      path: '/silabus/home'
      fullPath: '/silabus/home'
      preLoaderRoute: typeof LensSilabusHomeRouteImport
      parentRoute: typeof LensRouteRoute
    }
    '/_lens/super-admin/home': {
      id: '/_lens/super-admin/home'
      path: '/super-admin/home'
      fullPath: '/super-admin/home'
      preLoaderRoute: typeof LensSuperAdminHomeRouteImport
      parentRoute: typeof LensRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface LensRouteRouteChildren {
  LensHomeRoute: typeof LensHomeRoute
  LensAkademikAdminHomeRoute: typeof LensAkademikAdminHomeRoute
  LensExampleHomeRoute: typeof LensExampleHomeRoute
  LensExampleMockRoute: typeof LensExampleMockRoute
  LensExampleMockServerRoute: typeof LensExampleMockServerRoute
  LensKurikulumHomeRoute: typeof LensKurikulumHomeRoute
  LensPenilaianHomeRoute: typeof LensPenilaianHomeRoute
  LensPerkuliahanHomeRoute: typeof LensPerkuliahanHomeRoute
  LensPortofolioHomeRoute: typeof LensPortofolioHomeRoute
  LensSilabusHomeRoute: typeof LensSilabusHomeRoute
  LensSuperAdminHomeRoute: typeof LensSuperAdminHomeRoute
}

const LensRouteRouteChildren: LensRouteRouteChildren = {
  LensHomeRoute: LensHomeRoute,
  LensAkademikAdminHomeRoute: LensAkademikAdminHomeRoute,
  LensExampleHomeRoute: LensExampleHomeRoute,
  LensExampleMockRoute: LensExampleMockRoute,
  LensExampleMockServerRoute: LensExampleMockServerRoute,
  LensKurikulumHomeRoute: LensKurikulumHomeRoute,
  LensPenilaianHomeRoute: LensPenilaianHomeRoute,
  LensPerkuliahanHomeRoute: LensPerkuliahanHomeRoute,
  LensPortofolioHomeRoute: LensPortofolioHomeRoute,
  LensSilabusHomeRoute: LensSilabusHomeRoute,
  LensSuperAdminHomeRoute: LensSuperAdminHomeRoute,
}

const LensRouteRouteWithChildren = LensRouteRoute._addFileChildren(
  LensRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  LensRouteRoute: LensRouteRouteWithChildren,
  SplatRoute: SplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
